# Generated by Django 4.1.1 on 2022-09-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanbanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardName', models.CharField(default='some_text', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columnName', models.CharField(default='some_text', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtaskTitle', models.CharField(default='some_text', max_length=30)),
                ('isCompleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='taskDescription',
            field=models.CharField(default='some_text', max_length=99),
        ),
        migrations.AddField(
            model_name='task',
            name='taskStatus',
            field=models.CharField(default='some_text', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='taskTitle',
            field=models.CharField(default='some_text', max_length=30),
        ),
    ]
